####################################################################################
# Vincent Yasi
# CS 370 -Intro to Security
# Programming Assignment 2
#
# This file contains the program for Programming Assignment 2.
# Requires the Python modules <pyqrcode> and <pyotp> to be installed
#
# It takes in one of two commands and runs the appropriate function for it.
# The commands are <generate-qr> for generating a QR code from credentials
# for use with Google Authenticator,
# and <get_otp> to generate the OTP generated by Google Authenticator
# and display it to user.
#
# To run program, use "python submission.py <command>"
##################################################################################

import pyotp
import pyqrcode
from pyqrcode import QRCode
import sys
from generate_qr import generate_qr
from get_otp import get_otp

if sys.argv[1] == "generate-qr":
	generate_qr()

elif sys.argv[1] == "get-otp":
	get_otp()

else:
	print("Incorrect command")
	print("Program must be run as: python submission.py <command>")
	print("Acceptable commands are:")
	print("generate-qr")
	print("get-otp")